export const GET_ACTIVITY = 'GET_ACTIVITY';
export const FAILED_GET_ACTIVITY = 'FAILED_GET_ACTIVITY'
export const LOADING_GET_ACTIVITY = 'LOADING_GET_ACTIVITY'
export const TOOGLE_ACTIVATE = 'TOOGLE_ACTIVATE'
export const ADD_CHOSEN_ACTIVITY = "ADD_CHOSEN_ACTIVITY"
